import type { RoundDef, Question } from '../types'

const uid = () => Math.random().toString(36).slice(2, 9)

const quizQuestions: Question[] = [
  // THE OBVIOUS ONES
  { id: uid(), category: 'THE OBVIOUS ONES', text: 'What is her go-to comfort food when she\'s having a bad day?' },
  { id: uid(), category: 'THE OBVIOUS ONES', text: 'Which streaming service does she use the most?' },
  { id: uid(), category: 'THE OBVIOUS ONES', text: 'What is the first thing she does when she wakes up in the morning?' },
  { id: uid(), category: 'THE OBVIOUS ONES', text: 'How does she take her coffee or chai?' },
  { id: uid(), category: 'THE OBVIOUS ONES', text: 'What is her most-used emoji?' },
  { id: uid(), category: 'THE OBVIOUS ONES', text: 'What kind of music does she play when getting ready?' },
  { id: uid(), category: 'THE OBVIOUS ONES', text: 'What is her current phone wallpaper?' },
  // YOU SHOULD KNOW THIS
  { id: uid(), category: 'YOU SHOULD KNOW THIS', text: 'What is her biggest fear?' },
  { id: uid(), category: 'YOU SHOULD KNOW THIS', text: 'What is the one thing she can\'t leave the house without?' },
  { id: uid(), category: 'YOU SHOULD KNOW THIS', text: 'What does she do when she\'s anxious or stressed?' },
  { id: uid(), category: 'YOU SHOULD KNOW THIS', text: 'What is her biggest pet peeve?' },
  { id: uid(), category: 'YOU SHOULD KNOW THIS', text: 'What subject in school was she actually good at?' },
  { id: uid(), category: 'YOU SHOULD KNOW THIS', text: 'Who is her celebrity crush?' },
  // ONLY PEOPLE CLOSE TO HER KNOW
  { id: uid(), category: 'ONLY CLOSE PEOPLE KNOW', text: 'What is she most insecure about but would never admit?' },
  { id: uid(), category: 'ONLY CLOSE PEOPLE KNOW', text: 'What\'s her guilty pleasure TV show that she\'s embarrassed about?' },
  { id: uid(), category: 'ONLY CLOSE PEOPLE KNOW', text: 'What does she do when she thinks no one is watching?' },
  { id: uid(), category: 'ONLY CLOSE PEOPLE KNOW', text: 'What is the most dramatic thing she\'s ever cried about?' },
  { id: uid(), category: 'ONLY CLOSE PEOPLE KNOW', text: 'What is a habit she has that she\'s been trying to stop for years?' },
  { id: uid(), category: 'ONLY CLOSE PEOPLE KNOW', text: 'What\'s a compliment she secretly loves hearing?' },
  // WHAT WOULD SHE CHOOSE?
  { id: uid(), category: 'WHAT WOULD SHE CHOOSE?', text: 'Mountains or beach?', options: ['Mountains', 'Beach'] },
  { id: uid(), category: 'WHAT WOULD SHE CHOOSE?', text: 'Sleep in or early morning?', options: ['Sleep in', 'Early morning'] },
  { id: uid(), category: 'WHAT WOULD SHE CHOOSE?', text: 'Big party or intimate dinner?', options: ['Big party', 'Intimate dinner'] },
  { id: uid(), category: 'WHAT WOULD SHE CHOOSE?', text: 'Cook at home or eat out?', options: ['Cook at home', 'Eat out'] },
  { id: uid(), category: 'WHAT WOULD SHE CHOOSE?', text: 'Spontaneous trip or planned vacation?', options: ['Spontaneous trip', 'Planned vacation'] },
  { id: uid(), category: 'WHAT WOULD SHE CHOOSE?', text: 'Call or text?', options: ['Call', 'Text'] },
  { id: uid(), category: 'WHAT WOULD SHE CHOOSE?', text: 'Dogs or cats?', options: ['Dogs', 'Cats'] },
  { id: uid(), category: 'WHAT WOULD SHE CHOOSE?', text: 'Early flight or late-night drive?', options: ['Early flight', 'Late-night drive'] },
  { id: uid(), category: 'WHAT WOULD SHE CHOOSE?', text: 'Shopping alone or with a friend?', options: ['Alone', 'With a friend'] },
  { id: uid(), category: 'WHAT WOULD SHE CHOOSE?', text: 'Speak 5 languages or play 5 instruments?', options: ['Speak 5 languages', 'Play 5 instruments'] },
]

const whoSaidThisQuestions: Question[] = [
  { id: uid(), statement: '"I am not hungry." (while eating everyone else\'s food)', text: 'Who typically says this?', correctAnswer: '' },
  { id: uid(), statement: '"I\'ll be ready in 5 minutes."', text: 'Who typically says this?', correctAnswer: '' },
  { id: uid(), statement: '"I don\'t care, you decide." (then has a very strong opinion)', text: 'Who typically says this?', correctAnswer: '' },
  { id: uid(), statement: '"I literally told you this would happen."', text: 'Who typically says this?', correctAnswer: '' },
  { id: uid(), statement: '"This is the last time I\'m buying something I don\'t need."', text: 'Who typically says this?', correctAnswer: '' },
  { id: uid(), statement: '"I\'m not even that tired." (5 minutes before falling asleep)', text: 'Who typically says this?', correctAnswer: '' },
  { id: uid(), statement: '"We should do this more often." (then doesn\'t respond to messages for a week)', text: 'Who typically says this?', correctAnswer: '' },
  { id: uid(), statement: '"I\'m fine." (is clearly not fine)', text: 'Who typically says this?', correctAnswer: '' },
  { id: uid(), statement: '"Let\'s leave in 10 minutes." (leaves in 45)', text: 'Who typically says this?', correctAnswer: '' },
  { id: uid(), statement: '"I don\'t need help." (immediately needs help)', text: 'Who typically says this?', correctAnswer: '' },
]

const actLikeHerPrompts: Question[] = [
  { id: uid(), prompt: 'Act like her when she\'s getting ready and everyone has been waiting for 30 minutes.' },
  { id: uid(), prompt: 'Act like her when she sees the bill at a restaurant.' },
  { id: uid(), prompt: 'Act like her when someone wakes her up before she\'s ready.' },
  { id: uid(), prompt: 'Act like her ordering at a restaurant — for the 12th time because she keeps changing her mind.' },
  { id: uid(), prompt: 'Act like her when she says "I\'m fine" but is very obviously not fine.' },
  { id: uid(), prompt: 'Act like her talking to someone she doesn\'t like but has to be polite to.' },
  { id: uid(), prompt: 'Act like her when she sees something expensive that she really wants.' },
  { id: uid(), prompt: 'Act like her when she is angry but trying to seem calm.' },
  { id: uid(), prompt: 'Act like her explaining why a purchase was actually a very reasonable decision.' },
  { id: uid(), prompt: 'Act like her when she\'s running late and it\'s somehow everyone else\'s fault.' },
  { id: uid(), prompt: 'Act like her when she\'s pretending to listen but is completely distracted.' },
  { id: uid(), prompt: 'Act like her when she receives a compliment and doesn\'t know what to do with it.' },
  { id: uid(), prompt: 'Act like her scrolling through her phone at 2am when she should be asleep.' },
  { id: uid(), prompt: 'Act like her at the airport — specifically at security.' },
  { id: uid(), prompt: 'Act like her when she\'s trying to be healthy but someone mentions dessert.' },
]

const mostLikelyQuestions: Question[] = [
  { id: uid(), text: 'Who is most likely to spontaneously book a trip tomorrow without telling anyone?' },
  { id: uid(), text: 'Who is most likely to become insanely rich?' },
  { id: uid(), text: 'Who is most likely to get married first?' },
  { id: uid(), text: 'Who is most likely to have the most dramatic life story in 10 years?' },
  { id: uid(), text: 'Who is most likely to move to another country?' },
  { id: uid(), text: 'Who is most likely to spend ₹10,000 without realizing it?' },
  { id: uid(), text: 'Who is most likely to start a successful business?' },
  { id: uid(), text: 'Who is most likely to become famous?' },
  { id: uid(), text: 'Who is most likely to call Mom first in any situation?' },
  { id: uid(), text: 'Who is most likely to survive a zombie apocalypse?' },
  { id: uid(), text: 'Who is most likely to become the strictest parent?' },
  { id: uid(), text: 'Who is most likely to go 24 hours without their phone?' },
  { id: uid(), text: 'Who is most likely to win an argument they were completely wrong about?' },
  { id: uid(), text: 'Who is most likely to still be best friends with everyone in this room in 20 years?' },
  { id: uid(), text: 'Who is most likely to end up on a reality TV show?' },
]

const memoryQuestions: Question[] = [
  { id: uid(), text: 'What happened on the most chaotic family vacation we\'ve ever taken?', category: 'FAMILY LORE' },
  { id: uid(), text: 'What is the most embarrassing thing that happened to her as a child that she still gets reminded about?', category: 'CHILDHOOD' },
  { id: uid(), text: 'What was her first reaction when something really big happened in her life?', category: 'MILESTONES' },
  { id: uid(), text: 'What is a moment from her childhood that she has mentioned more than once?', category: 'MEMORIES' },
  { id: uid(), text: 'Describe exactly what she was wearing the last time she made everyone laugh really hard.', category: 'INSIDE JOKES' },
  { id: uid(), text: 'What is the story behind her most-told childhood memory?', category: 'FAMILY LORE' },
  { id: uid(), text: 'What happened the last time we all celebrated something together?', category: 'RECENT MEMORIES' },
  { id: uid(), text: 'What is an inside joke in this family/group that only we would understand?', category: 'INSIDE JOKES' },
  { id: uid(), text: 'What is something she did as a kid that makes everyone smile when they think about it?', category: 'CHILDHOOD' },
  { id: uid(), text: 'What is the one moment she probably wishes we would all forget?', category: 'EMBARRASSING' },
]

const heartQuestions: Question[] = [
  { id: uid(), text: 'What do you think makes her happiest when she doesn\'t say anything at all?' },
  { id: uid(), text: 'What is one thing you think she needs to hear right now, today?' },
  { id: uid(), text: 'What do you admire about her that you\'ve never quite said out loud?' },
  { id: uid(), text: 'What is something you think she is more capable of than she realizes?' },
  { id: uid(), text: 'What is one thing you genuinely hope happens for her this year?' },
  { id: uid(), text: 'What is something she does for others that she probably doesn\'t give herself credit for?' },
  { id: uid(), text: 'What is one memory with her that you would choose to relive, if you could?' },
  { id: uid(), text: 'What is one thing you will always be grateful to her for?' },
  { id: uid(), text: 'What do you think she is most proud of, even if she\'d never say it?' },
  { id: uid(), text: 'Finish this sentence: "The world is a little better because she..."' },
]

const finalMemoryPrompts: Question[] = [
  { id: uid(), text: 'Write something you love about her that you never usually say.' },
  { id: uid(), text: 'Describe one memory with her that you\'ll carry forever.' },
  { id: uid(), text: 'Write one thing you hope she gets, does, or feels this year.' },
  { id: uid(), text: 'Finish this: "You probably don\'t know this about yourself, but..."' },
  { id: uid(), text: 'Write one honest thing about what she means to you.' },
]

export function buildDefaultRounds(): RoundDef[] {
  return [
    {
      id: 'quiz',
      label: 'WHO KNOWS HER BEST?',
      number: '01',
      tagline: 'Okay… who really knows her?',
      description: 'Think you know her? Every answer counts. The birthday girl reveals the truth.',
      backgroundMode: 'light',
      questions: quizQuestions,
      currentQuestionIndex: 0,
      phase: 'intro',
    },
    {
      id: 'who-said-this',
      label: 'WHO SAID THIS?',
      number: '02',
      tagline: 'Someone in this room definitely said this.',
      description: 'A quote appears. You guess who said it. The answer might surprise you.',
      backgroundMode: 'light',
      questions: whoSaidThisQuestions,
      currentQuestionIndex: 0,
      phase: 'intro',
    },
    {
      id: 'act-like-her',
      label: 'ACT LIKE HER',
      number: '03',
      tagline: 'Channel your inner her.',
      description: 'A prompt appears. One player performs. The birthday girl is the judge.',
      backgroundMode: 'blush',
      questions: actLikeHerPrompts,
      currentQuestionIndex: 0,
      phase: 'intro',
    },
    {
      id: 'most-likely',
      label: 'MOST LIKELY TO',
      number: '04',
      tagline: 'The family has spoken.',
      description: 'A scenario appears. Everyone votes for who is most likely. No hiding.',
      backgroundMode: 'blush',
      questions: mostLikelyQuestions,
      currentQuestionIndex: 0,
      phase: 'intro',
    },
    {
      id: 'memory',
      label: 'HOW WELL DO YOU REMEMBER?',
      number: '05',
      tagline: 'Memory unlocked.',
      description: 'A question about a shared memory. Answer carefully — the real story is coming.',
      backgroundMode: 'light',
      questions: memoryQuestions,
      currentQuestionIndex: 0,
      phase: 'intro',
    },
    {
      id: 'heart',
      label: 'WHO KNOWS HER HEART?',
      number: '06',
      tagline: 'No points. Just truth.',
      description: 'Anonymous answers. Emotional questions. She\'ll read them one by one.',
      backgroundMode: 'dark',
      questions: heartQuestions,
      currentQuestionIndex: 0,
      phase: 'intro',
    },
    {
      id: 'photo',
      label: 'GUESS THE PHOTO',
      number: '07',
      tagline: 'A picture worth a thousand stories.',
      description: 'A memory from the past. Answer what you remember about it.',
      backgroundMode: 'dark',
      questions: [
        { id: uid(), text: 'How old was she in this photo?', photoUrl: '', photoYear: '', photoLocation: '', photoStory: '' },
        { id: uid(), text: 'Where was this photo taken?', photoUrl: '', photoYear: '', photoLocation: '', photoStory: '' },
        { id: uid(), text: 'What was happening the day this was taken?', photoUrl: '', photoYear: '', photoLocation: '', photoStory: '' },
      ],
      currentQuestionIndex: 0,
      phase: 'intro',
    },
    {
      id: 'final-memory',
      label: 'FINAL MEMORY ROUND',
      number: '08',
      tagline: 'Write something you don\'t usually say.',
      description: 'One message. From you to her. She reads them alone.',
      backgroundMode: 'warm-dark',
      questions: finalMemoryPrompts,
      currentQuestionIndex: 0,
      phase: 'intro',
    },
  ]
}
